allprojects {
    repositories {
        maven {
            url "https://repository-cdn.liferay.com/nexus/content/groups/public"
        }
    }
}

tasks.register("dockerDeployAll") {
    dependsOn(
        ":modules:todo-list-api:dockerCopyDeploy",
        ":modules:todo-list-service:dockerCopyDeploy",
        ":modules:todo-list-web:dockerCopyDeploy"
    )
}
