/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.todolist.model.impl;

import br.com.seatecnologia.todolist.model.Subtask;
import br.com.seatecnologia.todolist.model.SubtaskModel;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Subtask service. Represents a row in the &quot;SEA_Subtask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>SubtaskModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtaskImpl}.
 * </p>
 *
 * @author Carlos
 * @see SubtaskImpl
 * @generated
 */
public class SubtaskModelImpl
	extends BaseModelImpl<Subtask> implements SubtaskModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtask model instance should use the <code>Subtask</code> interface instead.
	 */
	public static final String TABLE_NAME = "SEA_Subtask";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"subtaskId", Types.BIGINT},
		{"taskId", Types.BIGINT}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"title", Types.VARCHAR},
		{"isCompleted", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("subtaskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("taskId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("isCompleted", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table SEA_Subtask (uuid_ VARCHAR(75) null,subtaskId LONG not null primary key,taskId LONG,createDate DATE null,modifiedDate DATE null,title VARCHAR(75) null,isCompleted BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table SEA_Subtask";

	public static final String ORDER_BY_JPQL =
		" ORDER BY subtask.subtaskId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY SEA_Subtask.subtaskId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean ENTITY_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean FINDER_CACHE_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static final boolean COLUMN_BITMASK_ENABLED = true;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long TASKID_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SUBTASKID_COLUMN_BITMASK = 4L;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		br.com.seatecnologia.todolist.service.util.ServiceProps.get(
				"lock.expiration.time.br.com.seatecnologia.todolist.model.Subtask"));

	public SubtaskModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _subtaskId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setSubtaskId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _subtaskId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Subtask.class;
	}

	@Override
	public String getModelClassName() {
		return Subtask.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Subtask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Subtask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subtask, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Subtask)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Subtask, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Subtask, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Subtask)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Subtask, Object>>
		getAttributeGetterFunctions() {

		return AttributeGetterFunctionsHolder._attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Subtask, Object>>
		getAttributeSetterBiConsumers() {

		return AttributeSetterBiConsumersHolder._attributeSetterBiConsumers;
	}

	private static class AttributeGetterFunctionsHolder {

		private static final Map<String, Function<Subtask, Object>>
			_attributeGetterFunctions;

		static {
			Map<String, Function<Subtask, Object>> attributeGetterFunctions =
				new LinkedHashMap<String, Function<Subtask, Object>>();

			attributeGetterFunctions.put("uuid", Subtask::getUuid);
			attributeGetterFunctions.put("subtaskId", Subtask::getSubtaskId);
			attributeGetterFunctions.put("taskId", Subtask::getTaskId);
			attributeGetterFunctions.put("createDate", Subtask::getCreateDate);
			attributeGetterFunctions.put(
				"modifiedDate", Subtask::getModifiedDate);
			attributeGetterFunctions.put("title", Subtask::getTitle);
			attributeGetterFunctions.put(
				"isCompleted", Subtask::getIsCompleted);

			_attributeGetterFunctions = Collections.unmodifiableMap(
				attributeGetterFunctions);
		}

	}

	private static class AttributeSetterBiConsumersHolder {

		private static final Map<String, BiConsumer<Subtask, Object>>
			_attributeSetterBiConsumers;

		static {
			Map<String, BiConsumer<Subtask, ?>> attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<Subtask, ?>>();

			attributeSetterBiConsumers.put(
				"uuid", (BiConsumer<Subtask, String>)Subtask::setUuid);
			attributeSetterBiConsumers.put(
				"subtaskId", (BiConsumer<Subtask, Long>)Subtask::setSubtaskId);
			attributeSetterBiConsumers.put(
				"taskId", (BiConsumer<Subtask, Long>)Subtask::setTaskId);
			attributeSetterBiConsumers.put(
				"createDate",
				(BiConsumer<Subtask, Date>)Subtask::setCreateDate);
			attributeSetterBiConsumers.put(
				"modifiedDate",
				(BiConsumer<Subtask, Date>)Subtask::setModifiedDate);
			attributeSetterBiConsumers.put(
				"title", (BiConsumer<Subtask, String>)Subtask::setTitle);
			attributeSetterBiConsumers.put(
				"isCompleted",
				(BiConsumer<Subtask, Boolean>)Subtask::setIsCompleted);

			_attributeSetterBiConsumers = Collections.unmodifiableMap(
				(Map)attributeSetterBiConsumers);
		}

	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@Override
	public long getSubtaskId() {
		return _subtaskId;
	}

	@Override
	public void setSubtaskId(long subtaskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_subtaskId = subtaskId;
	}

	@Override
	public long getTaskId() {
		return _taskId;
	}

	@Override
	public void setTaskId(long taskId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_taskId = taskId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalTaskId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("taskId"));
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_title = title;
	}

	@Override
	public boolean getIsCompleted() {
		return _isCompleted;
	}

	@Override
	public boolean isIsCompleted() {
		return _isCompleted;
	}

	@Override
	public void setIsCompleted(boolean isCompleted) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_isCompleted = isCompleted;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Subtask.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Subtask toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Subtask>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		SubtaskImpl subtaskImpl = new SubtaskImpl();

		subtaskImpl.setUuid(getUuid());
		subtaskImpl.setSubtaskId(getSubtaskId());
		subtaskImpl.setTaskId(getTaskId());
		subtaskImpl.setCreateDate(getCreateDate());
		subtaskImpl.setModifiedDate(getModifiedDate());
		subtaskImpl.setTitle(getTitle());
		subtaskImpl.setIsCompleted(isIsCompleted());

		subtaskImpl.resetOriginalValues();

		return subtaskImpl;
	}

	@Override
	public Subtask cloneWithOriginalValues() {
		SubtaskImpl subtaskImpl = new SubtaskImpl();

		subtaskImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		subtaskImpl.setSubtaskId(
			this.<Long>getColumnOriginalValue("subtaskId"));
		subtaskImpl.setTaskId(this.<Long>getColumnOriginalValue("taskId"));
		subtaskImpl.setCreateDate(
			this.<Date>getColumnOriginalValue("createDate"));
		subtaskImpl.setModifiedDate(
			this.<Date>getColumnOriginalValue("modifiedDate"));
		subtaskImpl.setTitle(this.<String>getColumnOriginalValue("title"));
		subtaskImpl.setIsCompleted(
			this.<Boolean>getColumnOriginalValue("isCompleted"));

		return subtaskImpl;
	}

	@Override
	public int compareTo(Subtask subtask) {
		long primaryKey = subtask.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Subtask)) {
			return false;
		}

		Subtask subtask = (Subtask)object;

		long primaryKey = subtask.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Subtask> toCacheModel() {
		SubtaskCacheModel subtaskCacheModel = new SubtaskCacheModel();

		subtaskCacheModel.uuid = getUuid();

		String uuid = subtaskCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			subtaskCacheModel.uuid = null;
		}

		subtaskCacheModel.subtaskId = getSubtaskId();

		subtaskCacheModel.taskId = getTaskId();

		Date createDate = getCreateDate();

		if (createDate != null) {
			subtaskCacheModel.createDate = createDate.getTime();
		}
		else {
			subtaskCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			subtaskCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			subtaskCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		subtaskCacheModel.title = getTitle();

		String title = subtaskCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			subtaskCacheModel.title = null;
		}

		subtaskCacheModel.isCompleted = isIsCompleted();

		return subtaskCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Subtask, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Subtask, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Subtask, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Subtask)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Subtask>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Subtask.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _subtaskId;
	private long _taskId;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _title;
	private boolean _isCompleted;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Subtask, Object> function =
			AttributeGetterFunctionsHolder._attributeGetterFunctions.get(
				columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Subtask)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("subtaskId", _subtaskId);
		_columnOriginalValues.put("taskId", _taskId);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("title", _title);
		_columnOriginalValues.put("isCompleted", _isCompleted);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("subtaskId", 2L);

		columnBitmasks.put("taskId", 4L);

		columnBitmasks.put("createDate", 8L);

		columnBitmasks.put("modifiedDate", 16L);

		columnBitmasks.put("title", 32L);

		columnBitmasks.put("isCompleted", 64L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Subtask _escapedModel;

}
