/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.todolist.model.impl;

import br.com.seatecnologia.todolist.model.Subtask;
import br.com.seatecnologia.todolist.service.SubtaskLocalServiceUtil;

/**
 * The extended model base implementation for the Subtask service. Represents a row in the &quot;SEA_Subtask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SubtaskImpl}.
 * </p>
 *
 * @author Carlos
 * @see SubtaskImpl
 * @see Subtask
 * @generated
 */
public abstract class SubtaskBaseImpl
	extends SubtaskModelImpl implements Subtask {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a subtask model instance should use the <code>Subtask</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			SubtaskLocalServiceUtil.addSubtask(this);
		}
		else {
			SubtaskLocalServiceUtil.updateSubtask(this);
		}
	}

}