/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.todolist.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Subtask service. Represents a row in the &quot;SEA_Subtask&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.todolist.model.impl.SubtaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.todolist.model.impl.SubtaskImpl</code>.
 * </p>
 *
 * @author Carlos
 * @see Subtask
 * @generated
 */
@ProviderType
public interface SubtaskModel extends BaseModel<Subtask> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a subtask model instance should use the {@link Subtask} interface instead.
	 */

	/**
	 * Returns the primary key of this subtask.
	 *
	 * @return the primary key of this subtask
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this subtask.
	 *
	 * @param primaryKey the primary key of this subtask
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this subtask.
	 *
	 * @return the uuid of this subtask
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this subtask.
	 *
	 * @param uuid the uuid of this subtask
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the subtask ID of this subtask.
	 *
	 * @return the subtask ID of this subtask
	 */
	public long getSubtaskId();

	/**
	 * Sets the subtask ID of this subtask.
	 *
	 * @param subtaskId the subtask ID of this subtask
	 */
	public void setSubtaskId(long subtaskId);

	/**
	 * Returns the task ID of this subtask.
	 *
	 * @return the task ID of this subtask
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this subtask.
	 *
	 * @param taskId the task ID of this subtask
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the create date of this subtask.
	 *
	 * @return the create date of this subtask
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this subtask.
	 *
	 * @param createDate the create date of this subtask
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this subtask.
	 *
	 * @return the modified date of this subtask
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this subtask.
	 *
	 * @param modifiedDate the modified date of this subtask
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this subtask.
	 *
	 * @return the title of this subtask
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this subtask.
	 *
	 * @param title the title of this subtask
	 */
	public void setTitle(String title);

	/**
	 * Returns the is completed of this subtask.
	 *
	 * @return the is completed of this subtask
	 */
	public boolean getIsCompleted();

	/**
	 * Returns <code>true</code> if this subtask is is completed.
	 *
	 * @return <code>true</code> if this subtask is is completed; <code>false</code> otherwise
	 */
	public boolean isIsCompleted();

	/**
	 * Sets whether this subtask is is completed.
	 *
	 * @param isCompleted the is completed of this subtask
	 */
	public void setIsCompleted(boolean isCompleted);

	@Override
	public Subtask cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}