/**
 * SPDX-FileCopyrightText: (c) 2026 Liferay, Inc. https://liferay.com
 * SPDX-License-Identifier: LGPL-2.1-or-later OR LicenseRef-Liferay-DXP-EULA-2.0.0-2023-06
 */

package br.com.seatecnologia.todolist.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Task service. Represents a row in the &quot;SEA_Task&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>br.com.seatecnologia.todolist.model.impl.TaskModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>br.com.seatecnologia.todolist.model.impl.TaskImpl</code>.
 * </p>
 *
 * @author Carlos
 * @see Task
 * @generated
 */
@ProviderType
public interface TaskModel
	extends BaseModel<Task>, GroupedModel, ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a task model instance should use the {@link Task} interface instead.
	 */

	/**
	 * Returns the primary key of this task.
	 *
	 * @return the primary key of this task
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this task.
	 *
	 * @param primaryKey the primary key of this task
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this task.
	 *
	 * @return the uuid of this task
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this task.
	 *
	 * @param uuid the uuid of this task
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the task ID of this task.
	 *
	 * @return the task ID of this task
	 */
	public long getTaskId();

	/**
	 * Sets the task ID of this task.
	 *
	 * @param taskId the task ID of this task
	 */
	public void setTaskId(long taskId);

	/**
	 * Returns the group ID of this task.
	 *
	 * @return the group ID of this task
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this task.
	 *
	 * @param groupId the group ID of this task
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this task.
	 *
	 * @return the company ID of this task
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this task.
	 *
	 * @param companyId the company ID of this task
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this task.
	 *
	 * @return the user ID of this task
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this task.
	 *
	 * @param userId the user ID of this task
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this task.
	 *
	 * @return the user uuid of this task
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this task.
	 *
	 * @param userUuid the user uuid of this task
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this task.
	 *
	 * @return the user name of this task
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this task.
	 *
	 * @param userName the user name of this task
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this task.
	 *
	 * @return the create date of this task
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this task.
	 *
	 * @param createDate the create date of this task
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this task.
	 *
	 * @return the modified date of this task
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this task.
	 *
	 * @param modifiedDate the modified date of this task
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the title of this task.
	 *
	 * @return the title of this task
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this task.
	 *
	 * @param title the title of this task
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this task.
	 *
	 * @return the description of this task
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this task.
	 *
	 * @param description the description of this task
	 */
	public void setDescription(String description);

	/**
	 * Returns the is completed of this task.
	 *
	 * @return the is completed of this task
	 */
	public boolean getIsCompleted();

	/**
	 * Returns <code>true</code> if this task is is completed.
	 *
	 * @return <code>true</code> if this task is is completed; <code>false</code> otherwise
	 */
	public boolean isIsCompleted();

	/**
	 * Sets whether this task is is completed.
	 *
	 * @param isCompleted the is completed of this task
	 */
	public void setIsCompleted(boolean isCompleted);

	/**
	 * Returns the is deleted of this task.
	 *
	 * @return the is deleted of this task
	 */
	public boolean getIsDeleted();

	/**
	 * Returns <code>true</code> if this task is is deleted.
	 *
	 * @return <code>true</code> if this task is is deleted; <code>false</code> otherwise
	 */
	public boolean isIsDeleted();

	/**
	 * Sets whether this task is is deleted.
	 *
	 * @param isDeleted the is deleted of this task
	 */
	public void setIsDeleted(boolean isDeleted);

	/**
	 * Returns the due date of this task.
	 *
	 * @return the due date of this task
	 */
	public Date getDueDate();

	/**
	 * Sets the due date of this task.
	 *
	 * @param dueDate the due date of this task
	 */
	public void setDueDate(Date dueDate);

	/**
	 * Returns the image ID of this task.
	 *
	 * @return the image ID of this task
	 */
	public long getImageId();

	/**
	 * Sets the image ID of this task.
	 *
	 * @param imageId the image ID of this task
	 */
	public void setImageId(long imageId);

	/**
	 * Returns the category ID of this task.
	 *
	 * @return the category ID of this task
	 */
	public long getCategoryId();

	/**
	 * Sets the category ID of this task.
	 *
	 * @param categoryId the category ID of this task
	 */
	public void setCategoryId(long categoryId);

	@Override
	public Task cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}