sourceCompatibility = "1.8"
targetCompatibility = "1.8"

dependencies {
	compileOnly group: "com.liferay.portal", name: "release.portal.api", version: "7.4.3.112-ga112"

	compileOnly project(":modules:todo-list-api")

	testImplementation group: "junit", name: "junit", version: "4.13.2"
	testImplementation group: "org.mockito", name: "mockito-core", version: "4.11.0"
	testImplementation group: "org.mockito", name: "mockito-inline", version: "4.11.0"

	testImplementation group: "com.liferay.portal", name: "release.portal.api", version: "7.4.3.112-ga112"
	testImplementation project(":modules:todo-list-api")
}

buildService {
	apiDir = "../todo-list-api/src/main/java"
}

task dockerCopyDeploy(type: Exec, dependsOn: jar) {
	commandLine "docker", "cp",
		jar.archiveFile.get().asFile.absolutePath,
		"todolist-liferay:/opt/liferay/osgi/modules/${jar.archiveFileName.get()}"
}
